---
language: node_js
jobs:
  include:
  - dist: focal
    node_js: '20'
  - dist: focal
    node_js: '19'
  - dist: focal
    node_js: '18'
  - node_js: '16'
  - node_js: '14'

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn test
