---
language: node_js
node_js:
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn test
