---
language: node_js
node_js:
  - dist: focal
    node_js: '19'
  - dist: focal
    node_js: '18'
  - '16'
  - '14'

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn test
