module.exports = {
  allEqual: require('./all-equal'),
  argsToObj: require('./args-to-obj'),
  containsAll: require('./contains-all'),
  defaultToStrict: require('./default-to-strict'),
  ensureArray: require('./ensure-array'),
  equalsAny: require('./equals-any'),
  evolveArray: require('./evolve-array'),
  flattenShallow: require('./flatten-shallow'),
  format: require('./format'),
  fpThrow: require('./fp-throw'),
  isNilOrEmpty: require('./is-nil-or-empty'),
  isNot: require('./is-not'),
  isPopulatedString: require('./is-populated-string'),
  list: require('./list'),
  mergeSpec: require('./merge-spec'),
  mergeWithArrays: require('./merge-with-arrays'),
  propOrStrict: require('./prop-or-strict'),
  renameKeys: require('./rename-keys'),
  replaceAll: require('./replace-all'),
  stringToBoolean: require('./string-to-boolean'),
  testHarness: require('./test-harness'),
  trace: require('./trace'),
};
